[tool.black]
line-length = 90
include = '\.pyi?$'
target-version = ['py312']
exclude = '''
/(
  \.git
 | \.hg
 | \.mypy_cache
 | \.tox
 | \.venv
 | \.Lib
 | \.Scripts
 | env
 | venv
 | _build
 | buck-out
 | build
 | dist
)/
'''